version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf  # Автосоздание БД
      - INFLUXDB_HTTP_AUTH_ENABLED=false  # Отключаем аутентификацию для тестов
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  telegraf:
    image: telegraf:1.27
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      influxdb:
        condition: service_healthy

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      influxdb:
        condition: service_healthy

volumes:
  influxdb_data:
  grafana_data: